### ISSUE TITLE
Unsupported binary script has syntax error

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-docker#22]
CI will add a script that outputs an unsupported message for binaries that on a platform that is unsupported. (e.g. sensu-backend on `linux/386`) The script that is created currently contains a syntax error that should be fixed: https://github.com/sensu/sensu-docker/blob/main/.circleci/config.yml#L184-L200

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/opt-sensu-bin-sensu-backend-line-3-syntax-error-unterminated-quoted-string-on-armv7-raspberry-pi/2528/2

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/opt-sensu-bin-sensu-backend-line-3-syntax-error-unterminated-quoted-string-on-armv7-raspberry-pi/2528/4
