### ISSUE TITLE
Generate random password for init by default

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-docker#5]
Use a generated password to use with `sensu-backend init` by default and send it to STDOUT. Skip the generation of the password when `SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD` is set.

It may make more sense to do this in `sensu-go` for all uses of `sensu-backend init`, not just the Docker container.

**Comment by calebhailey** [comment]
Closing in favor of #28 (and maybe also https://github.com/sensu/sensu-enterprise-go/issues/1727)
